### ISSUE TITLE
setup-python failing due to missing cache directory

### ISSUE THREAD

**Issue by wmmc88** [actions/setup-python#328]
**Description:**
[This job](https://github.com/wmmc88/PrusaSlicer-FlashForge/runs/4999966360?check_suite_focus=true) on my repo has been failing since #303 was merged in. Only the python 11 alpha variant is failing due to a cache related issue for pip. It fails in the `Post Setup Python` stage.

**Action version:** `master`

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ x] Windows

**Runner type:**
- [x ] Hosted
- [ ] Self-hosted

**Tools version:**

python 3.11.0-alpha

**Repro steps:**  
Run any pipeline with python 3.11.0-alpha on windows.

**Expected behavior:**
The job should succeed.

The job fails on `Post Setup Python`

**Comment by hugovk** [comment]
I'm seeing it too, also Windows and 3.11 alpha:

* https://github.com/hugovk/pypistats/runs/5015794619?check_suite_focus=true
* https://github.com/hugovk/pypistats/pull/311

I don't think #303 has been released yet, `v2` is still pointing to `v2.3.1` from November:

* https://github.com/actions/setup-python/tags

Possibly linked to the release of pip 22 on Sunday?

**Comment by wmmc88** [comment]
hm. yeah I assumed it was due to #303 because I use the master tag for `setup-python` and the failure coincided with the merging of the #303, but looks like you're right in that its not released to v2 and u have the same issue on v2.

**Comment by MaksimZhukov** [comment]
Hello @wmmc88! Thank you for the report!
We are investigating the issue. We will come back with investigation results as soon as we have them.

**Comment by dmitry-shibanov** [comment]
Hello @wmmc88. Thank you for your report. It's partly related to these changes, but the root cause is different. Previously cache key for pip didn't contain version of the python, that is why cache got hit on the primary key and the action didn't resave it. Now primary and restore keys have been changed and it forces action to resave cache.
I've added some more debug logs and found that the `pip cache dir` for python 3.11.0-alpha.4 (latest pip in general) returns output to stderr not to the stdout. I'm not sure the issue itself related to setup-python or pip. For now we continue investigation.

**Comment by janosh** [comment]
[Could this error](https://github.com/janosh/pdf-compressor/runs/5051115721?check_suite_focus=true#step:3:9) have a similar cause?

```
Run actions/setup-python@v2
  with:
    python-version: 3.8
    cache: pip
    cache-dependency-path: setup.cfg
    token: ***
Successfully setup CPython (3.8.10)
C:\hostedtoolcache\windows\Python\3.8.10\x64
Error: The process 'C:\hostedtoolcache\windows\Python\3.8.10\x64\Scripts\pip.exe' failed with exit code 322122
```

**Comment by dmitry-shibanov** [comment]
Hello @janosh. Yes, It's related to this issue: https://github.com/actions/toolkit/issues/992
I'm not sure, but it's also can be related to this issue: https://github.com/pypa/pip/issues/10875

**Comment by jku** [comment]
From what I can tell the failures started as windows image updated https://github.com/actions/virtual-environments/issues/5009

**Comment by dmitry-shibanov** [comment]
Hello everyone. We released new version with fix ([2.3.2](https://github.com/actions/setup-python/releases/tag/v2.3.2)). Could you please try to use it and confirm if it works for you?

**Comment by felixxm** [comment]
> Hello everyone. We released new version with fix ([2.3.2](https://github.com/actions/setup-python/releases/tag/v2.3.2)). Could you please try to use it and confirm if it works for you?

Thanks :+1: Unfortunately, it still [crashes](https://github.com/django/django/runs/5065644849?check_suite_focus=true) for us :cry: .

**Comment by janosh** [comment]
@dmitry-shibanov [Same here](https://github.com/janosh/pdf-compressor/runs/5065877995?check_suite_focus=true#step:3:9), also still crashing.

**Comment by jku** [comment]
> Thanks +1 Unfortunately, it still [crashes](https://github.com/django/django/runs/5065644849?check_suite_focus=true) for us cry .

Note that they've not updated the v2 tag (forgot?) so you are probably not testing the new version.

My issue was fixed with the Windows workaround, if I modify my workflow to use setup-python@v2.3.2 (instead of @v2):
https://github.com/theupdateframework/python-tuf/runs/5065875026

**Comment by janosh** [comment]
@jku I thought `setup-python@v2` would us the latest version in that major version tag?

**Comment by dmitry-shibanov** [comment]
Hello @janosh. For now we have not updated the tag v2. 
Thank you for your confirmation @jku.

**Comment by jku** [comment]
> @jku I thought `setup-python@v2` would us the latest version in that major version tag?

That maybe the intended policy but the tag "v2" currently points to release "v2.3.1".

**Comment by hugovk** [comment]
✅  Confirmed fixed with `actions/setup-python@v2.3.2`:

* Before: https://github.com/hugovk/pypistats/actions/runs/1777756911
* Change: https://github.com/hugovk/pypistats/commit/908c98679803712afa05b2d767bd25f7f49c7a81
* After: https://github.com/hugovk/pypistats/actions/runs/1794899283

Thank you!

**Comment by dmitry-shibanov** [comment]
Hello everyone. We updated v2 tag. Could you please confirm that everything works as expected ?

**Comment by wmmc88** [comment]
> Hello everyone. We updated v2 tag. Could you please confirm that everything works as expected ?

My issues fixed!

**Comment by hugovk** [comment]
✅ `v2` fixed, thanks again!

* https://github.com/hugovk/pypistats/actions/runs/1777756911

**Comment by felixxm** [comment]
It works for us :rocket: Many thanks :1st_place_medal:

**Comment by webknjaz** [comment]
FTR, the hack inspired by this issue introduced an intermittent bug in the action when new versions of pip are being published: https://github.com/actions/setup-python/issues/1034.
