### ISSUE TITLE
Version 3.10 with arch x64 not found

### ISSUE THREAD

**Issue by BlueskyFR** [actions/setup-python#401]
**Description:**
Version 3.10 with arch x64 is not found when running on self-hosted runner.

**Action version:** latest

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**

3.10, altough it seems like all versions are affected

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
```yml
- name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
```

**Expected behavior:**
Version should be fetched correctly.

**Actual behavior:**
The 3.10 version for x64 exists but the error says otherwise.

**Comment by dsame** [comment]
hello @BlueskyFR , can you please provide addional info about the ubuntu version of self-hosted runner?

**Comment by BlueskyFR** [comment]
Sure, it is actually not Ubuntu but Debian Buster

**Comment by dsame** [comment]
@BlueskyFR while i am reproducing the problem can please try quick solution of the setting AGENT_TOOLSDIRECTORY to `/opt/hostedtoolcache` (i assume you still use Debian), namely:

```
- name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"
       env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
```

If this helps the original issue should be solved as soon as   https://github.com/actions/setup-python/pull/394 merged

**Comment by TechDawg270** [comment]
I am still experiencing the issue. Tried both with the env var mentioned above, and also without
`- uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache`

**Comment by dsame** [comment]
@BlueskyFR @TechDawg270 

It is confirmed the problem relates to Debian boosters

[Succees on Ubuntu-20](https://github.com/akv-demo/setup-python-test/actions/runs/2336510889)
[Fail on Debian 10.12](https://github.com/akv-demo/setup-python-test/actions/runs/2336525559)

We need a bit more time to investigate the problem with the specific distro

**Comment by deepankur797** [comment]
@dsame For me it is failing even on Ubuntu-20.04

Description:
Version 3.10 with arch x64 is not found when running on act locally.

Action version: latest

Platform:

- [x] Ubuntu

Runner type:

- [x] Locally

Tools version:

3.10, although it seems like all versions are affected

Repro steps:
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

`      - name: setup python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: "3.x"
          cache: "pip"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache`

Expected behaviour:
The version should be fetched correctly.

Actual behaviour:
The 3.10 version for x64 exists but the error says otherwise.

**Comment by dsame** [comment]
@deepankur797 , thanks for you input, can you please add the exact step you use to setup python?

**Comment by deepankur797** [comment]
I have used the following code in my job
```

steps:
  -name: setup python
   uses: actions/setup-python@v3
   with:
     python-version: "3.x"
     cache: "pip"
   env:
     AGENT_TOOLSDIRECTORY: /opt/hostedtoolache
```

**Comment by dsame** [comment]
@BlueskyFR @TechDawg270

The short story: Debian is not supported, sorry

 So the only workaround is - either to use Ubuntu for self-hosted machine (any virtualisation works fine) or to install python from the Debian specific repositories. 

Long story: 
 The exact reason is the [parsing /etc/os-release and extracting VERSION_ID](https://github.com/actions/toolkit/blob/b5f31bb5a25d129441c294fc81ba7f92f3e978ba/packages/tool-cache/src/manifest.ts#L140): while we expect one of "18.04", "20.04" or "22.04" the debian provides "10" and there's no python matched to this version id. 

 The worst part is we hardly can to fix the code because the python from tool cache is built against the libraries specific to the distribution and there's no certainty that the python will work the libraries from the other distribution.

**Comment by dsame** [comment]
@deepankur797 

The step[ works without problem](https://github.com/akv-demo/setup-python-test/runs/6804470081?check_suite_focus=true) on Ubuntu 20.04

```
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
```

Can you please confirm you created `opt/hostedtoolcache` folder and grant the write permission to the user of the runner  on this folder?

**Comment by dsame** [comment]
@BlueskyFR @TechDawg270

PR https://github.com/actions/toolkit/pull/1112 adds the debug message to clarify the reason the action fails. It is the best we can do for now according to the issue.

**Comment by dsame** [comment]
Hello @BlueskyFR i am going to close this issue because it seems to be resolved and there's no other comments so far. Feel free to open new issue or reopen this one in case of any problem

**Comment by Yarden-zmr** [comment]
To be clear, other distros are officially NOT supported?

**Comment by dsame** [comment]
Hello @Yarden-zmr ,

You are right. All the binaries are built against Ubuntu provided packages.

**Comment by floptical** [comment]
This is currently failing with Python3.10 and trying to use the latest ubuntu version (which I'm reading is 22.04) from Github-hosted runners. Tried the following:

With v3:
```
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
```
 
Error:

```
Version 3.1 was not found in the local cache
Error: Version 3.1 with arch x[6](https://github.com/CityOfPhiladelphia/voter_registration_address_analysis/actions/runs/6191546006/job/16809997757#step:2:7)4 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

With v4:

```
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
```

Error:

```
Version 3.1 was not found in the local cache
Error: The version '3.1' with architecture 'x64' was not found for Ubuntu 22.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by francesco-ballarin** [comment]
> This is currently failing with Python3.10 and trying to use the latest ubuntu version (which I'm reading is 22.04) from Github-hosted runners. Tried the following:
> ...
> ```
> jobs:
>   deploy:
>     name: deploy
>     runs-on: ubuntu-latest
>     steps:
>       - name: Setup Python 3.10
>         uses: actions/setup-python@v4
>         with:
>           python-version: 3.10
> ```
> 
> Error:
> ```
> Version 3.1 was not found in the local cache
> Error: The version '3.1' with architecture 'x64' was not found for Ubuntu 22.04.
> The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
> ```

The solution is to quote 3.10, i.e.
```
       - name: Setup Python 3.10
         uses: actions/setup-python@v4
         with:
           python-version: "3.10"
```
otherwise it gets interpreted as a floating point number, and 3.10 (or 3.100, for that matter) becomes 3.1.


Answering a few months later, because I had the same issue and searching on google for `"Version 3.1 was not found in the local cache"` has the above post as the first link in the results.

**Comment by rwader-swi** [comment]
why is this issue closed? It is still not supported for debian even when python versions are available

**Comment by akuzminsky** [comment]
For me, it fails on Ubuntu oracular. Works on Ubuntu noble.

**Comment by aparnajyothi-y** [comment]
Hello everyone, The setup-python action supports running Python on GitHub-hosted runners, which are based on Ubuntu, macOS, and Windows environments, as outlined in the[ documentation](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-setup-python-with-a-self-hosted-runner). However, certain Linux distributions, such as Debian, are not officially supported. This is because the pre-built Python binaries provided by GitHub Actions are tailored to specific distributions (like Ubuntu) and rely on distribution-specific libraries. As a result, using setup-python on Debian may lead to compatibility issues.

To work around this and support Debian, you can use Ubuntu-based self-hosted runners (virtualization works fine).

Please feel free to reach out if you have any concerns or need further clarification.

**Comment by aparnajyothi-y** [comment]
Hello Everyone, Please let us know in case of any further concerns/clarifications are needed on the above information

**Comment by lmmx** [comment]
Not caught up on the context here but I am finding this occurs for me when running `act` to try to run GitHub Actions locally. 

> I used `mise use act` to get act:
> 
> ```bash
> curl https://mise.run | sh
> echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.bashrc
> source ~/.bashrc
> ```

I ran this on my repo to run [its workflow](https://github.com/lmmx/powell-opt/blob/abf0a3781e06f096f6c1b610de6544d5e547bcb5/.github/workflows/CI.yml):

```bash
mise use act
act -j linux
```

```
[CI/linux-6     ] ⭐ Run Main actions/setup-python@v5
[CI/linux-6     ]   🐳  docker cp src=/home/louis/.cache/act/actions-setup-python@v5/ dst=/var/run/act/actions/actions-setup-python@v5/
[CI/linux-6     ]   🐳  docker exec cmd=[/usr/local/bin/node /var/run/act/actions/actions-setup-python@v5/dist/setup/index.js] user= workdir=
[CI/linux-6     ]   ❓  ::group::Installed versions
| Failed to resolve version 3.10 from manifest
| Version 3.10 was not found in the local cache
[CI/linux-5     ]   ❗  ::error::The version '3.10' with architecture 'x64' was not found for this operating system.%0AThe list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
[CI/linux-5     ]   ❌  Failure - Main actions/setup-python@v5 [904.328416ms]
[CI/linux-5     ] exitcode '1': failure
[CI/linux-5     ] ⭐ Run Complete job
[CI/linux-5     ]   ✅  Success - Complete job
[CI/linux-5     ] 🏁  Job failed
| Failed to resolve version 3.10 from manifest
| Version 3.10 was not found in the local cache
[CI/linux-6     ]   ❗  ::error::The version '3.10' with architecture 'x64' was not found for this operating system.%0AThe list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
[CI/linux-6     ]   ❌  Failure - Main actions/setup-python@v5 [847.627548ms]
```

**Comment by v-aparnajyothi-y** [comment]
Hello @lmmx, Thank you for the issue with detailed logs and as mentioned in the above comments Setup-python action is designed to support GitHub-hosted runners based on Ubuntu, macOS, and Windows environments, as outlined in the [official GitHub documentation](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners)

However, certain Linux distributions, such as Debian, are not officially supported. This is because the pre-built Python binaries provided by GitHub Actions are tailored to specific distributions (like Ubuntu) and rely on distribution-specific libraries. As a result, using setup-python on Debian may lead to compatibility issues.

Please feel free to reach out if you have any concerns or need further clarification.

**Comment by lmmx** [comment]
> Setup-python action is designed to support GitHub-hosted runners based on Ubuntu…

> certain Linux distributions, such as Debian, are not officially supported.

> using setup-python on Debian may lead to compatibility issues

I am on an Ubuntu-based distro and am using Ubuntu images in Docker, so I am using Ubuntu, not Debian.

I am using Ubuntu 22.04/Jammy docker images running on `act` which runs the Docker images. I said this.

**Comment by v-aparnajyothi-y** [comment]
Hello @lmmx, thank you for the clarification and additional context.
You're right in pointing out that you're using an Ubuntu-based distribution and Ubuntu Docker images with act. However, it's important to note that the setup-python action relies on pre-built binaries and a manifest (versions-manifest.json) tailored specifically for GitHub-hosted runners. These runners have certain environment guarantees (like pre-installed dependencies and directory structures) that act does not fully replicate, even if the Docker image is Ubuntu-based.
In your case, the error:
The version '3.10' with architecture 'x64' was not found for this operating system
indicates that the setup-python action couldn't find a compatible Python binary matching the environment simulated by act. This is a known limitation when running actions locally with act, especially for actions that depend on tightly controlled hosted runner environments like setup-python.
Please feel free to reach out in case further concerns or clarifications are required.

**Comment by aparnajyothi-y** [comment]
Hello @lmmx, thank you for the clarification and additional context.
You're right in pointing out that you're using an Ubuntu-based distribution and Ubuntu Docker images with act. However, it's important to note that the setup-python action relies on pre-built binaries and a manifest (versions-manifest.json) tailored specifically for GitHub-hosted runners. These runners have certain environment guarantees (like pre-installed dependencies and directory structures) that act does not fully replicate, even if the Docker image is Ubuntu-based.
In your case, the error:
The version '3.10' with architecture 'x64' was not found for this operating system
indicates that the setup-python action couldn't find a compatible Python binary matching the environment simulated by act. This is a known limitation when running actions locally with act, especially for actions that depend on tightly controlled hosted runner environments like setup-python.
Please feel free to reach out in case further concerns or clarifications are required.

**Comment by v-aparnajyothi-y** [comment]
Hello @lmmx, Please let us know in case of any further concerns/clarifications are needed on the above information

**Comment by lmmx** [comment]
> it's important to note that the setup-python action relies on pre-built binaries and a manifest (versions-manifest.json) tailored specifically for GitHub-hosted runners.

But [you support self-hosted runners](https://docs.github.com/en/actions/concepts/runners/self-hosted-runners) (I am unsure why you have posted above the docs about GitHub-hosted runners when both are supported). It sounds almost like you're saying support for self-hosted runners is being dropped, in contradiction to the docs.

The software is meant to run on Ubuntu, but has the bug report of it not doing so, it seems like a bug and so should not have been closed as resolved (which is being justified on the basis that the reports were only for Debian, but then that was extended when also reported on Ubuntu to say that the reports were not on GitHub runners, even when self-hosted runners are meant to be supported too).

> These runners have certain environment guarantees (like pre-installed dependencies and directory structures) that act does not fully replicate, even if the Docker image is Ubuntu-based. In your case, the error: The version '3.10' with architecture 'x64' was not found for this operating system indicates that the setup-python action couldn't find a compatible Python binary matching the environment simulated by act.

With respect, this is circular logic and not actionable.

I know it was not found, the point of submitting this error report was to inquire with you, the maintainer of the software emitting the error, as to **where** precisely in the system the mismatch was occurring. It is typical to receive some assistance in locating the source of the error, you appear to be primarily seeking to declare it unsupported so as to close the issue without resolving the bug report. I am perplexed why supporting the use of this software for local testing before deployment is not a priority for its maintainers, it makes the developer experience significantly worse to not know in advance if your Action logic is sound.

> This is a known limitation when running actions locally with act

I see no tracking issue where this has been reported and declared resolved or fair game to just be ignored. I see nothing in the docs warning users not to use it with `act`. Dismissing this bug report and declaring it "known" without any further info leaves me as a user without a resolution. Perhaps you could share more of what is known about it, perhaps link me to where this has been discussed previously, because this was my first interaction with this bug tracker. Obviously I wouldn't be reporting it if I knew the solution, and it blocked me from developing with the `setup-python` action.

I looked up the issue here and I find various other reports but it just seems to be users suggesting fixes to each other, not maintainers clarifying what the users are doing wrong. Links in case they help others find the solution in their cases:

- Here 2 weeks ago: https://github.com/actions/setup-python/issues/750#issuecomment-3181520486
- Here as recently as January: https://github.com/actions/setup-python/issues/162
- Here last year: https://github.com/actions/setup-python/issues/913#issuecomment-2268242732
- Here in 2023: https://github.com/actions/setup-python/issues/541

The maintainer previously closed it on this condition:

> i am going to close this issue because it seems to be resolved and there's no other comments so far. Feel free to open new issue or reopen this one in case of any problem

So I believe this issue should be reopened.
